---
neutron_logging_debug: False
dhcp_agents_per_network: 3
rpc_transport_url:
  "rabbit://guest:Mx9iDzzpRboRrtSAHruOmQuXb@overcloud-controller-0.internalapi.localdomain:5672/?ssl=0"
designate_ns_record: openstacklocal
notify_transport_url:
  "rabbit://guest:Mx9iDzzpRboRrtSAHruOmQuXb@overcloud-controller-0.internalapi.localdomain:5672/?ssl=0"
neutron_plugin_agent: openvswitch
# The directory to merge custom config files the kolla's config files
node_config_config: /etc/large_scale/config
neutron_server_port: "9696"
