---
- name: Restart fake neutron-openvswitch-agent container
  become: true
  docker_container:
    state: started
    restart: true
    name: "neutron_openvswitch_agent_fake_{{ item }}"
    image: "{{ neutron_openvswitch_agent_image }}"
    network_mode: host
    privileged: True
    env:
      KOLLA_CONFIG_STRATEGY: "COPY_ALWAYS" #copy config from host to docker
    volumes:
      - "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/var/log/large_scale/neutron/:/var/log/neutron/"
  register: check_fake_neutron_openvswitch_agent
  with_sequence: "start=1 end={{ num_nova_fake_per_node }}"
