---
# - name: Restart fake neutron-openvswitch-agent container
#   vars:
#     service_name: "neutron-openvswitch-agent"
#     service: "{{ neutron_services[service_name] }}"
#     config_json: "{{ neutron_config_jsons.results|selectattr('item.key', 'equalto', service_name)|first }}"
#     neutron_conf: "{{ neutron_confs.results|selectattr('item.key', 'equalto', service_name)|first }}"
#     neutron_ml2_conf: "{{ neutron_ml2_confs.results|selectattr('item.key', 'equalto', service_name)|first }}"
#     policy_json: "{{ policy_jsons.results|selectattr('item.key', 'equalto', service_name)|first }}"
#     neutron_openvswitch_agent_container: "{{ check_neutron_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
#   become: true
#   kolla_docker:
#     action: "recreate_or_restart_container"
#     common_options: "{{ docker_common_options }}"
#     name: "{{ service.container_name }}"
#     image: "{{ service.image }}"
#     volumes: "{{ service.volumes }}"
#     dimensions: "{{ service.dimensions }}"
#     privileged: "{{ service.privileged | default(False) }}"
#   with_sequence: "start=1 end={{ num_nova_fake_per_node }}"
#   when:
#     - kolla_action != "config"
#     - enable_nova_fake | bool
#     - neutron_plugin_agent == "openvswitch"
#     - inventory_hostname in groups["compute"]
#     - fake_config_json | changed
#       or fake_neutron_conf | changed
#       or fake_neutron_ml2_conf_ini | changed
#       or check_fake_neutron_openvswitch_agent | changed

- name: Restart fake neutron-openvswitch-agent container
  vars:
    service_name: "neutron-openvswitch-agent"
    service: "{{ neutron_services[service_name] }}"
    config_json: "{{ neutron_config_jsons.results|selectattr('item.key', 'equalto', service_name)|first }}"
    neutron_conf: "{{ neutron_confs.results|selectattr('item.key', 'equalto', service_name)|first }}"
    neutron_ml2_conf: "{{ neutron_ml2_confs.results|selectattr('item.key', 'equalto', service_name)|first }}"
    policy_json: "{{ policy_jsons.results|selectattr('item.key', 'equalto', service_name)|first }}"
    neutron_openvswitch_agent_container: "{{ check_neutron_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  become: true
  docker_container:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    privileged: "{{ service.privileged | default(False) }}"
  with_sequence: "start=1 end={{ num_nova_fake_per_node }}"
  when:
    - enable_nova_fake | bool
    - neutron_plugin_agent == "openvswitch"
    - inventory_hostname in groups["compute"]
    - fake_config_json | changed
      or fake_neutron_conf | changed
      or fake_neutron_ml2_conf_ini | changed
      or check_fake_neutron_openvswitch_agent | changed
