---
- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}"
    state: "directory"
    recurse: yes
    mode: "0770"
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  # when: inventory_hostname in groups['compute']

- name: Copying over config.json files for services
  become: true
  template:
    src: "neutron-openvswitch-agent.json.j2"
    dest: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/config.json"
    mode: "0660"
  register: fake_config_json
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  when:
    # - inventory_hostname in groups['compute']
    - neutron_plugin_agent == "openvswitch"

- name: Copying over neutron.conf
  become: true
  vars:
    service_name: "{{ item }}"
  template:
    sources:
      - "{{ role_path }}/templates/neutron.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/neutron.conf"
      - "{{ node_custom_config }}/neutron/{{ item }}.conf"
      # - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron.conf"
    dest: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/neutron.conf"
    mode: "0660"
  register: fake_neutron_conf
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  when:
    # - inventory_hostname in groups['compute']
    - neutron_plugin_agent == "openvswitch"

- name: Copying over ml2_conf.ini
  become: true
  vars:
    service_name: "{{ item }}"
  template:
    sources:
      - "{{ role_path }}/templates/ml2_conf.ini.j2"
      - "{{ node_custom_config }}/neutron/ml2_conf.ini"
      # - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron.conf"
    dest: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/ml2_conf.ini"
    mode: "0660"
  register: fake_neutron_ml2_conf_ini
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  when:
    # - inventory_hostname in groups['compute']
    - neutron_plugin_agent == "openvswitch"

- name: Checking neutron-openvswitch-agent container for nova fake node
  vars:
    neutron_openvswitch_agent: "{{ neutron_services['neutron-openvswitch-agent'] }}"
  become: true
  docker_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ neutron_openvswitch_agent.container_name }}"
    image: "{{ neutron_openvswitch_agent.image }}"
    privileged: "{{ neutron_openvswitch_agent.privileged | default(False) }}"
    volumes: "{{ neutron_openvswitch_agent.volumes }}"
  register: check_fake_neutron_openvswitch_agent
  with_sequence: "start=1 end={{ num_nova_fake_per_node }}"
  notify:
    - Restart fake neutron-openvswitch-agent container

- name: Ensuring config directory has correct owner and permission
  become: true
  file:
    path: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  # when: inventory_hostname in groups['compute']
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
