---
- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}"
    state: "directory"
    recurse: yes
    mode: "0770"
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  # when: inventory_hostname in groups['compute']
  notify:
  - Restart fake neutron-openvswitch-agent container

- name: Copying over config.json files for services
  become: true
  template:
    src: "neutron-openvswitch-agent.json.j2"
    dest: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/config.json"
    mode: "0660"
  register: fake_config_json
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  when:
    # - inventory_hostname in groups['compute']
    - neutron_plugin_agent == "openvswitch"
  notify:
  - Restart fake neutron-openvswitch-agent container

- name: Copying over neutron.conf
  become: true
  template:
    src: "neutron.conf.j2"
    dest: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/neutron.conf"
    mode: "0660"
  register: fake_neutron_conf
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  notify:
    - Restart fake neutron-openvswitch-agent container

- name: Copying over ml2_conf.ini
  become: true
  template:
    src: "ml2_conf.ini.j2"
    dest: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/ml2_conf.ini"
    mode: "0660"
  register: fake_neutron_ml2_conf_ini
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  notify:
    - Restart fake neutron-openvswitch-agent container

- name: Ensuring config directory has correct owner and permission
  become: true
  file:
    path: "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}"
    recurse: yes
    owner: root
    group: root
  with_sequence: start=1 end={{ num_nova_fake_per_node }}

- name: Ensuring log directory has correct owner and permission
  become: true
  file:
    path: "/var/log/large_scale/neutron/ovs-agent-fake-{{ item }}"
    recurse: yes
    state: directory
    owner: root
    group: root
  with_sequence: start=1 end={{ num_nova_fake_per_node }}

- name: Checking neutron-openvswitch-agent container for nova fake node
  become: true
  docker_container:
    state: started
    name: "neutron_openvswitch_agent_fake_{{ item }}"
    image: "{{ neutron_openvswitch_agent_image }}"
    network_mode: host
    privileged: True
    env:
      KOLLA_CONFIG_STRATEGY: "COPY_ALWAYS" #copy config from host to docker
    volumes:
      - "{{ node_config_directory }}/neutron-openvswitch-agent-fake-{{ item }}/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/var/log/large_scale/neutron/:/var/log/neutron/"
  register: check_fake_neutron_openvswitch_agent
  with_sequence: "start=1 end={{ num_nova_fake_per_node }}"
